### ISSUE TITLE
interruptions Mplabx

### ISSUE THREAD

**Issue by lb34000** [pololu/p-star-examples#2]
Hi David

have you ever tried to use int0/ int1    interruption on the  pstar board with the boot loader .
after 4 hours trying.....
it really suck  i can t enter in the interruption at all despite checking all registers ...
might be some pointer fuck up  with the code offset due to the boot loader ?? 

#include <xc.h>
#include <pic18f25k50.h>
#define _XTAL_FREQ 48000000

void interrupt Interruption (void) {
    INTCONbits.GIE=0;
    INTCONbits.INT0IF=0;
    INTCON3bits.INT1IF =0;
    LATC6 = 1;
}

void main() {

    TRISB = 0b00000011; 
    TRISC = 0; 

    INTCONbits.GIE = 1;   // ACTIVE LES INTERRUPT
    INTCONbits.INT0IE = 1; // ACTIVE L INTERRUPT int0 pin Rb0
    INTCON3bits.INT1IE = 1;  //active int1

    LATB7 = 0;
    LATB6 = 0;
    LATC6 = 1;

    
    
    __delay_ms(1000);
    LATB7 = 1;
    __delay_ms(1000);
    LATB6 = 1;
    __delay_ms(1000);
    LATC6 = 0;
    __delay_ms(1000);

    while(1)
    {
     LATB7 = 0;
    __delay_ms(1000);   
    }
    
   
}

Rgds

Gael

**Comment by DavidEGrayson** [comment]
For help programming the P-Star, please post on our [forum](https://forum.pololu.com/).  This area is for discussing bugs and features requests for the P-Star examples.
